config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'signins#create'
  post '/auth/:provider/callback', to: 'signins#create'
  get '/auth/failure', to: 'signins#create'
  get '/delete_identity/:provider', to: 'signins#remove', as: 'delete_identity'
  get 'p/:promo', to: 'promos#show', as: :promo

  get '/admin', to: 'admin/dashboard#show'
  namespace :admin do
    resources :areas do
      put 'reorder', on: :collection
    end
    resources :pages do
      put 'reorder', on: :collection
    end
    resources :comments
    resources :groups
    resources :users
    resources :skus
    resources :promos
    resources :themes
    resource :dashboard, only: [:show]
  end

  post 'upload', to: 'uploads#create'

  resources :areas, only: [:show]
  resource :user, only: [:new, :create, :edit, :update, :destroy] do
    get :deactivate
  end
  resources :comments
  resources :subscriptions

  get :signup, to: 'users#new', as: 'signup'
  resource :signin, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get :signin, to:  'signins#new'
  get :request_reset, to:  'signins#edit', as: :request_reset
  get :signout, to:  'signins#destroy'
  put :reset_password, to: 'signins#update', as: :reset_password
  get 'confirm/:token', to: 'signins#confirm', as: :confirm
  get 'profile', to: 'users#edit', as: :profile
  get 'sitemap.xml' => 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  get ':permalink', to: 'areas#show'
  root to: 'areas#show'
end

app/views/admin/pages/_form.html.erb
<h1><%= page.new_record? ? 'New Lesson' : 'Edit Lesson' %></h1>

<%= form_for([:admin, page], html: {id: 'editor_form'}) do |f| %>
  <div class='card'>

    <div class='card-block'>
      <% unless page.new_record? %>
        <%= link_to 'Delete',
          [:admin, page],
          method: :delete,
          class: 'btn btn-sm btn-danger-outline pull-xs-right',
          data: { confirm: "#{page.title} will be deleted. Are you sure?" } %>
      <% end %>
    </div>

    <div class='row'>
      <div class='col-sm-8'>
        <%= f.label :content, class: 'sr-only' %>
        <%= f.text_area :content, id: 'editor_content' %>
      </div>

      <div class='col-sm-4'>
        <div class='form-group row'>
          <fieldset class='publish'>
          <%= f.label :area_id, 'Course', class: 'form-control-label col-sm-2' %>
          <div class='col-sm-10'><%= f.collection_select :area_id, Area.all, :id, :name,{}, class: 'c-select' %></div>
          </fieldset>
        </div>

        <div class='form-group row'>
          <%= f.label :title, class: 'form-control-label col-sm-2' %>
          <div class='col-sm-10'><%= f.text_field :title, class: 'form-control' %></div>
        </div>

        <% if false %>
        <div class='form-group row'>
          <%= f.label 'Cover image', class: 'form-control-label col-sm-2' %>
          <div class='col-sm-10'><%= f.text_field :cover, class: 'form-control' %></div>
        </div>
        <% end %>

        <div class='form-group row'>
          <%= f.label :permalink, class: 'form-control-label col-sm-2' %>
          <div class='col-sm-10'><%= f.text_field :permalink, class: 'form-control' %></div>
        </div>

        <div class='form-group row'>
          <%= f.label :classes, class: 'form-control-label col-sm-2' %>
          <div class='col-sm-10'><%= f.text_field :classes, class: 'form-control' %></div>
        </div>

        <div class='form-group row'>
          <%= f.label :cover, class: 'form-control-label col-sm-2' %>
          <div class='col-sm-10'><%= f.text_field :cover, class: 'form-control' %></div>
        </div>

        <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

      </div>
    </div>
  </div>

<% end %>

app/views/admin/pages/_table.html.erb
<div class='card'>
  <div class='card-block'>
    <h4 class="card-title">Lessons</h4>
  </div>
  <div class='card-block'>

    <table class='table table-hover table-striped table-sm' data-sort-url='<%= admin_pages_url %>' data-current-sort-column='<%= @current_sort_column %>' data-sort-dir='<%= @sort_dir %>'>
      <thead>
        <tr>
          <th data-sort-column='title'>Title</th>
          <!-- <th data-sort-column='users.last_name'>By</th> -->
          <% if @area.nil? %><th data-sort-column='areas.name'>Area</th><% end %>
          <!-- <th data-sort-column='permalink'>Permalink</th> -->
          <th data-sort-column='commentable'>Comments</th>
          <th data-sort-column='publish'>Ready</th>
          <th data-sort-column='published_at'>Published at</th>
          <th data-sort-column='pull_at'>Pull at</th>
          <th data-sort-column='impressions_count'>Views</th>
          <th></th>
        </tr>
      </thead>

      <tbody data-sortable='<%= reorder_admin_pages_url %>'>
        <% @pages.each do |page| %>
          <tr data-edit-id='<%= page.id %>'>
            <td data-field='title'><%= page.title.try(:truncate, 40) %></td>
            <!-- <td data-field='user_name'><%= page.user.name %></td> -->
            <% if @area.nil? %><td data-field='area_name'><%= page.area.name %></td><% end %>
            <!-- <td data-field='permalink'><%= page.permalink.try(:truncate, 10) %></td> -->
            <td data-field='commentable'><%= yes_no page.commentable %></td>
            <td data-field='publish'><%= yes_no page.publish %></td>
            <td data-field='published_at'><i class='fa fa-clock-o'></i> <%= page.published_at.nil? ? "&mdash;".html_safe : page.published_at.to_date.strftime('%b %e, %y') %></td>
            <td data-field='pull_at'><%= page.pull_at.nil? ? "&mdash;".html_safe : "<i class='fa fa-clock-o'></i> #{page.pull_at.to_date.strftime('%b %e, %y')}".html_safe %></td>
            <td data-field='impressions_count'><%= page.impressions.count %></td>
            <td><%= link_to icon('pencil'), edit_admin_page_path(page) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='card-block'>
    <%= link_to new_admin_page_path(area_id: @area), class: 'btn btn-primary' do %>
      <i class='fa fa-plus'></i> Add Lesson
    <% end %>
  </div>
</div>

app/views/admin/pages/edit.html.erb
<%= render 'shared/errors', object: @page %>

<div id='container' class='text-xs-center'>
  <%= render 'form', page: @page %>
</div>

app/views/admin/pages/index.html.erb
<div class='content-container'>
  <h1>Pages</h1>
  <%= render 'table' %>

  <% content_for :modals do %>
    <div class="modal fade" id="form_modal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <%= render 'form', page: Page.new %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/pages/new.html.erb
<%= render 'shared/errors', object: @page %>

<div id='container' class='text-xs-center'>
  <%= render 'form', page: @page %>
</div>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @page.user.try(:name) %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @page.cover %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<p>
  <strong>Area:</strong>
  <%= @page.area.try(:name) %>
</p>

<p>
  <strong>Commentable:</strong>
  <%= @page.commentable %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @page.properties %>
</p>

<p>
  <strong>Position:</strong>
  <%= @page.position %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @page.publish %>
</p>

<p>
  <strong>Views:</strong>
  <%= @page.impressions.count %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @page.published_at %>
</p>

<p>
  <strong>Pull at:</strong>
  <%= @page.pull_at %>
</p>

<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>