config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'signins#create'
  post '/auth/:provider/callback', to: 'signins#create'
  get '/auth/failure', to: 'signins#create'
  get '/delete_identity/:provider', to: 'signins#remove', as: 'delete_identity'
  get 'p/:promo', to: 'promos#show', as: :promo

  get '/admin', to: 'admin/dashboard#show'
  namespace :admin do
    resources :areas do
      put 'reorder', on: :collection
    end
    resources :pages do
      put 'reorder', on: :collection
    end
    resources :comments
    resources :groups
    resources :users
    resources :skus
    resources :promos
    resources :themes
    resource :dashboard, only: [:show]
  end

  post 'upload', to: 'uploads#create'

  resources :areas, only: [:show]
  resource :user, only: [:new, :create, :edit, :update, :destroy] do
    get :deactivate
  end
  resources :comments
  resources :subscriptions

  get :signup, to: 'users#new', as: 'signup'
  resource :signin, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get :signin, to:  'signins#new'
  get :request_reset, to:  'signins#edit', as: :request_reset
  get :signout, to:  'signins#destroy'
  put :reset_password, to: 'signins#update', as: :reset_password
  get 'confirm/:token', to: 'signins#confirm', as: :confirm
  get 'profile', to: 'users#edit', as: :profile
  get 'sitemap.xml' => 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  get ':permalink', to: 'areas#show'
  root to: 'areas#show'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :page
  belongs_to :page
  belongs_to :in_response_to, class_name: 'Comment', foreign_key: 'parent_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'parent_id'
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:user_id, :page_id, :content, :submitted_at, :approved, :posted_at)
  end
end

app/views/admin/comments/_form.html.erb
<%= form_for([:admin, comment]) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :page_id %>
    <%= f.text_field :page_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :submitted_at %>
    <%= f.datetime_select :submitted_at %>
  </div>

  <div class="field">
    <%= f.label :approved %>
    <%= f.check_box :approved %>
  </div>

  <div class="field">
    <%= f.label :posted_at %>
    <%= f.datetime_select :posted_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', [:admin, @comment] %> |
<%= link_to 'Back', admin_comments_path %>

app/views/admin/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Page</th>
      <th>Content</th>
      <th>Submitted at</th>
      <th>Approved</th>
      <th>Posted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.page %></td>
        <td><%= comment.content %></td>
        <td><%= comment.submitted_at %></td>
        <td><%= comment.approved %></td>
        <td><%= comment.posted_at %></td>
        <td><%= link_to 'Show', [:admin, comment] %></td>
        <td><%= link_to 'Edit', edit_admin_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', [:admin, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_admin_comment_path %>

app/views/admin/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', admin_comments_path %>

app/views/admin/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Page:</strong>
  <%= @comment.page %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Submitted at:</strong>
  <%= @comment.submitted_at %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @comment.approved %>
</p>

<p>
  <strong>Posted at:</strong>
  <%= @comment.posted_at %>
</p>

<%= link_to 'Edit', edit_admin_comment_path(@comment) %> |
<%= link_to 'Back', admin_comments_path %>