config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'signins#create'
  post '/auth/:provider/callback', to: 'signins#create'
  get '/auth/failure', to: 'signins#create'
  get '/delete_identity/:provider', to: 'signins#remove', as: 'delete_identity'
  get 'p/:promo', to: 'promos#show', as: :promo

  get '/admin', to: 'admin/dashboard#show'
  namespace :admin do
    resources :areas do
      put 'reorder', on: :collection
    end
    resources :pages do
      put 'reorder', on: :collection
    end
    resources :comments
    resources :groups
    resources :users
    resources :skus
    resources :promos
    resources :themes
    resource :dashboard, only: [:show]
  end

  post 'upload', to: 'uploads#create'

  resources :areas, only: [:show]
  resource :user, only: [:new, :create, :edit, :update, :destroy] do
    get :deactivate
  end
  resources :comments
  resources :subscriptions

  get :signup, to: 'users#new', as: 'signup'
  resource :signin, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get :signin, to:  'signins#new'
  get :request_reset, to:  'signins#edit', as: :request_reset
  get :signout, to:  'signins#destroy'
  put :reset_password, to: 'signins#update', as: :reset_password
  get 'confirm/:token', to: 'signins#confirm', as: :confirm
  get 'profile', to: 'users#edit', as: :profile
  get 'sitemap.xml' => 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  get ':permalink', to: 'areas#show'
  root to: 'areas#show'
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <script type="text/javascript">
    toastr.options = {
      'closeButton': false,
      'debug': false,
      'positionClass': 'toast-bottom-right',
      'onclick': null,
      'showDuration': '300',
      'hideDuration': '1000',
      'timeOut': '7000',
      'extendedTimeOut': '10000',
      'showEasing': 'swing',
      'hideEasing': 'linear',
      'showMethod': 'fadeIn',
      'hideMethod': 'fadeOut'
    }
    <% object.errors.full_messages.each do |message| %>
   	 toastr['error']('<%= message %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    toastr.options = {
      'closeButton': false,
      'debug': false,
      'positionClass': 'toast-top-center',
      'onclick': null,
      'showDuration': '300',
      'hideDuration': '1000',
      'timeOut': '7000',
      'extendedTimeOut': '10000',
      'showEasing': 'swing',
      'hideEasing': 'linear',
      'showMethod': 'fadeIn',
      'hideMethod': 'fadeOut'
    }
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   	 toastr['<%= type %>']('<%= f[1][0..150] %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class='text-center'>
      <% footer_items.each do |footer_item| %>
        <li><%= link_to footer_item.label, area_path(footer_item) %></li>
      <% end %>
    </ul>
  </div>
</footer>

app/views/shared/_icons.html.erb
<meta name="msapplication-TileColor" content="#921a1c">
<meta name="msapplication-TileImage" content="/mstile-150x150.png">
<meta name="theme-color" content="#EFE1C6">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#921a1c">

app/views/shared/_navigation.html.erb
<header class="main">
<div class="content">
  <h1><a class="logo" href="/"></a></h1>
</div>
</header>
<nav class="navbar navbar-dark bg-inverse">
  <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="logo" href="/"></a>
  <div id="navbar">
     <nav class="nav navbar-nav pull-xs-left">
      <%= link_to 'Admin', admin_path, class: 'nav-item nav-link' if current_user.try(:admin?) %>
      <!--<%= render(partial: 'shared/navitem', collection: nav_items) if Area.count %>-->
    </nav>
    <nav class="nav navbar-nav pull-xs-right">
      <% if current_user %>
        <%= link_to current_user.user_name, profile_path, class: 'nav-item nav-link' %>
        <%= link_to 'Sign out', signout_path, class: 'nav-item nav-link' %>
      <% elsif !current_page?(signin_path) %>
        <%= link_to 'Sign in', signin_path, class: 'nav-item nav-link' %>
      <% end %>
    </nav> 
    <!-- TODO: Replace search bar with user menu -->
    <!-- <form class="pull-xs-right"> -->
      <!-- <input type="text" class="form-control" placeholder="Search..."> -->
    <!-- </form> -->
  </div>
</nav>

app/views/shared/_navitem.html.erb
<%= link_to navitem.label, area_path(navitem.id), class: 'nav-item nav-link' %>

app/views/shared/_panel.html.erb
<div class='sidebar col-xs-3 col-md-2'>
  <ul class='nav nav-sidebar'>
    <%= nav_link 'Dashboard', admin_path, 'home' %>
    <%= nav_link 'Courses', admin_areas_path, 'filing' %>
    <%# nav_link 'Pages', admin_pages_path , 'document-text'%>
    <%# nav_link 'Groups', admin_groups_path, 'earth' %>
    <%= nav_link 'Themes', admin_themes_path, 'android-color-palette' %>
    <%= nav_link 'SKUs', admin_skus_path, 'ios-barcode-outline' %>
    <%= nav_link 'Promos', admin_promos_path, 'arrow-graph-up-right' %>
    <%= nav_link 'Users', admin_users_path, 'happy-outline' %>
  </ul>
</div>

app/views/shared/_social.html.erb
<div class='text-xs-center'>
  <div class="mar-btm"><em><%= "#{greeting} &#8230;".html_safe %></em></div>
  <%= link_to '/auth/facebook', class: 'btn btn-primary btn-xs' do %>
    <i class="fa fa-facebook"></i> Facebook
  <% end %>
  <%= link_to '/auth/twitter', class: 'btn btn-primary btn-xs' do %>
    <i class="fa fa-twitter"></i> Twitter
  <% end %>
  <%= link_to '/auth/google_oauth2', class: 'btn btn-primary btn-xs' do %>
    <i class="fa fa-google"></i> Google
  <% end %>
  <%= link_to '/auth/instagram', class: 'btn btn-primary btn-xs' do %>
    <i class="fa fa-instagram"></i> Instagram
  <% end %>
  <%= link_to '/auth/twitch', class: 'btn btn-primary btn-xs' do %>
    <i class="fa fa-twitch"></i> Twitch
  <% end %>
</div>