config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'signins#create'
  post '/auth/:provider/callback', to: 'signins#create'
  get '/auth/failure', to: 'signins#create'
  get '/delete_identity/:provider', to: 'signins#remove', as: 'delete_identity'
  get 'p/:promo', to: 'promos#show', as: :promo

  get '/admin', to: 'admin/dashboard#show'
  namespace :admin do
    resources :areas do
      put 'reorder', on: :collection
    end
    resources :pages do
      put 'reorder', on: :collection
    end
    resources :comments
    resources :groups
    resources :users
    resources :skus
    resources :promos
    resources :themes
    resource :dashboard, only: [:show]
  end

  post 'upload', to: 'uploads#create'

  resources :areas, only: [:show]
  resource :user, only: [:new, :create, :edit, :update, :destroy] do
    get :deactivate
  end
  resources :comments
  resources :subscriptions

  get :signup, to: 'users#new', as: 'signup'
  resource :signin, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get :signin, to:  'signins#new'
  get :request_reset, to:  'signins#edit', as: :request_reset
  get :signout, to:  'signins#destroy'
  put :reset_password, to: 'signins#update', as: :reset_password
  get 'confirm/:token', to: 'signins#confirm', as: :confirm
  get 'profile', to: 'users#edit', as: :profile
  get 'sitemap.xml' => 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  get ':permalink', to: 'areas#show'
  root to: 'areas#show'
end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :area
  belongs_to :course, class_name: 'Area', foreign_key: 'course_id'
  
  validates :name, presence: true
  validates :course, presence: true
  validates :stripe_coupon, presence: true
  
  def self.add_hit(promo_code)
    @promo = Promo.where(enabled: true).find_by_name promo_code
    @promo.add_hit if @promo
  end
  
  def self.add_conversion(promo_code)
    @promo = Promo.where(enabled: true).find_by_name promo_code
    @promo.add_conversion if @promo
  end
  
  def add_hit
    update hits: hits + 1
  end
  
  def add_conversion
    update conversions: conversions + 1
  end
  
  def rate
    hits > 0 ? (conversions / hits) : 0
  end
end

app/controllers/admin/promos_controller.rb
class Admin::PromosController < Admin::AdminController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
    if params[:order_by].present?
      @current_sort_column = params[:order_by]
      @sort_dir = params[:dir].blank? ? 'ASC' : params[:dir]
      @promos = @promos.order('%s %s' % [@current_sort_column, @sort_dir])
    end
    @promos = @promos.page(params[:page]).per(20)
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to admin_promos_path, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to admin_promos_path, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to admin_promos_path, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_promo
    @promo = Promo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def promo_params
    params.require(:promo).permit(:name, :course_id, :stripe_coupon, :enabled, :expires_on, :message)
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo

  def show
    if @promo
      @promo.add_hit unless cookies.encrypted[:promo].present?
      cookies.permanent.encrypted[:promo] = @promo.name

      # get coupon from Stripe
      # store discount value in cookie for arithmetic to display preview price
      @coupon = Stripe::Coupon.retrieve(@promo.stripe_coupon)
      unless @coupon.percent_off.nil?
        cookies.permanent[:promo_percent_off] = @coupon.percent_off
      end
      
      @url = friendly_area_url @promo.course
      flash[:notice] = @promo.message unless @promo.message.blank?
    end
    @url ||= root_url
    redirect_to @url
  end

  private

  def set_promo
    @promo = Promo.where(enabled: true).find_by_name params[:promo]
  end

end

app/views/admin/promos/_form.html.erb
<div class='modal-body'>
  <%= form_for([:admin, promo]) do |f| %>
    <h4 class='modal-title text-center' id='exampleModalLabel'><%= promo.new_record? ? 'New' : 'Edit' %>
      <span>Promo</span>
      <% unless promo.new_record? %>
        <%= link_to 'Delete',
          [:admin, promo],
          method: :delete,
          class: 'btn btn-sm btn-danger-outline pull-xs-right',
          data: { confirm: "#{promo.name} will be deleted. Are you sure?" } %>
      <% end %>
    </h4>

    <div class='form-group row'>
      <%= f.label :name, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.text_field :name, class: 'form-control' %></div>
    </div>

    <div class='form-group row'>
      <fieldset class='plan'>
      <%= f.label :course_id, 'Land on', class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.select :course_id, Area.all.map { |i| [i.name, i.id]}, {include_blank: false}, class: 'c-select' %></div>
      </fieldset>
    </div>

    <div class='form-group row'>
      <%= f.label :stripe_coupon, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.text_field :stripe_coupon, class: 'form-control' %></div>
    </div>

    <div class='form-group row'>
      <%= f.label :hits, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.text_field :hits, class: 'form-control', readonly: true %></div>
    </div>

    <div class='form-group row'>
      <%= f.label :conversions, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.text_field :conversions, class: 'form-control', readonly: true %></div>
    </div>

    <div class="form-group row">
      <div class='col-sm-2'>&nbsp;</div>
      <div class='col-sm-10'>
        <div class='checkbox'>
          <label>
            <%= f.check_box :enabled, class: 'form-control' %>
              Enabled
          </label>
        </div>
      </div>
    </div>

    <div class='form-group row'>
      <%= f.label :expires_on, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.date_select :expires_on, class: 'form-control' %></div>
    </div>

    <div class='form-group row'>
      <%= f.label :message, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.text_field :message, class: 'form-control' %></div>
    </div>

<% if false %>
    <div class='form-group row'>
      <%= f.label :price, 'Amount', class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.number_field :price, class: 'form-control', step: 'any' %></div>
    </div>

    <div class='form-group row'>
      <%= f.label :interval, class: 'form-control-label col-sm-2' %>
      <div class='col-sm-10'><%= f.select :interval, [['month', 'month'], ['year', 'year'], ['lifetime', 'lifetime']] %></div>
    </div>
  <% end %>
<% end %>
</div>

<div class='modal-footer'>
  <%= link_to 'Close', admin_skus_path, class: 'btn btn-secondary' %>
  <button type='button' class='btn btn-primary' data-form-submit='form'>Save</button>
</div>

app/views/admin/promos/edit.html.erb
<%= render 'form', promo: @promo %>

<%= render 'shared/errors', object: @promo %>

app/views/admin/promos/index.html.erb
<div class='content-container'>
  <h1>Promos</h1>

  <div class='card'>
    <div class='card-block'>
      <%= link_to '#', data: { toggle: 'modal', target: '#form_modal' }, class: 'btn btn-primary' do %>
        <i class='fa fa-plus'></i> Add Promo
      <% end %>
    </div>
    <div class='card-block'>

      <table class='table table-hover table-striped table-sm table-middle' data-sort-url='<%= admin_skus_url %>' data-current-sort-column='<%= @current_sort_column %>' data-sort-dir='<%= @sort_dir %>'>
        <thead>
          <tr>
            <th data-sort-column='enabled'>Enabled</th>
            <th data-sort-column='name'>Name</th>
            <th data-sort-column='course_id'>Landing</th>
            <th data-sort-column='stripe_coupon'>Stripe coupon</th>
            <th data-sort-column='message'>Message</th>
            <th data-sort-column='hits'>Hits</th>
            <th data-sort-column='conversions'>Conversions</th>
            <th>Rate</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @promos.each do |promo| %>
            <tr data-id='<%= promo.id %>'>
              <td data-row-click data-field='enabled'><%= icon('check') if promo.enabled %></td>
              <td data-row-click data-field='plan_id'><%= link_to icon('external-link-square', promo.name), promo_url(promo.name) %></td>
              <td data-row-click data-field='landing'><%= promo.course.name %></td>
              <td data-row-click data-field='stripe_coupon'><%= promo.stripe_coupon %></td>
              <td data-row-click data-field='hits'><%= truncate(promo.message, length: 40) %></td>
              <td data-row-click data-field='hits'><%= promo.hits %></td>
              <td data-row-click data-field='conversions'><%= promo.conversions %></td>
              <td data-row-click data-field='rate'><%= promo.rate > 0 ? number_to_percentage(promo.rate * 100, precision: 1) : '&mdash;'.html_safe %></td>
              <td><%= link_to icon('pencil'), edit_admin_promo_path(promo) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @promos %>
      <div class='row text-xs-right'></div>

    </div>
  </div>

  <% content_for :modals do %>
    <div class="modal fade" id="form_modal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <%= render 'form', promo: Promo.new %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/promos/new.html.erb
<%= render 'shared/errors', object: @promo %>

<%= render 'form', promo: @promo %>

app/views/admin/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @user.avatar %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Confirmed:</strong>
  <%= @user.confirmed %>
</p>

<p>
  <strong>Token:</strong>
  <%= @user.token %>
</p>

<p>
  <strong>Reset token:</strong>
  <%= @user.reset_token %>
</p>

<p>
  <strong>Reset at:</strong>
  <%= @user.reset_at %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Preferences:</strong>
  <%= @user.preferences %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>